name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci
      #- run: npm run build --if-present
      - run: npm install -g @angular/cli@16.2.16 # Install Angular CLI in the workflow environment
        working-directory: ./client
      - run: |
            cd client
            #npx npm-check-updates -u
            npm install
            ng build --configuration production

      # - name: Set up SSH
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"

      # - name: Add server to known hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -H ubuntu@ec2-18-207-191-94.compute-1.amazonaws.com >> ~/.ssh/known_hosts


      - run: |
            mkdir -p ~/.ssh   # Crea la carpeta ~/.ssh si no existe
            ssh-keyscan -H ec2-18-207-191-94.compute-1.amazonaws.com >> ~/.ssh/known_hosts
            cat ~/.ssh/known_hosts

      - run: |
            cd client
            ssh-keyscan -H ec2-18-207-191-94.compute-1.amazonaws.com >> ~/.ssh/known_hosts

            #sudo scp -o StrictHostKeyChecking=no -r ./dist /var/www/
            sudo scp -r ./dist/* ubuntu@ec2-18-207-191-94.compute-1.amazonaws.com:/var/www/
            sudo rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/ ubuntu@ec2-18-207-191-94.compute-1.amazonaws.com:/var/www/
            ssh ubuntu@ec2-18-207-191-94.compute-1.amazonaws.com

            ls -R dist

            #rsync -avz  ./client/dist/client/  ubuntu@ec2-18-207-191-94.compute-1.amazonaws.com:/var/www/
            #ssh  ubuntu@ec2-18-207-191-94.compute-1.amazonaws.com "sudo systemctl restart nginx"
            #sudo docker stop container-api-node
            sudo systemctl restart nginx
        shell: /usr/bin/bash -e {0}

      #- run: npm test




#------------------------------------------------------------
# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [ "dev" ]
#   pull_request:
#     branches: [ "dev" ]

# jobs:
#   start:
#     name: PULL
#     runs-on: self-hosted
#     # strategy:
#     #   matrix:
#     #     node-version: [18.x, 20.x, 22.x]
#     #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     steps:
#        - uses: actions/checkout@v4
#     #   - name: Use Node.js ${{ matrix.node-version }}
#     #   uses: actions/setup-node@v4
#     #   with:
#     #     node-version: ${{ matrix.node-version }}
#     #     cache: 'npm'
#         # cache: 'npm'
#         # - run: npm ci
#     #- run: npm run build --if-present
#     #- run: npm test

#       # - name: Build Angular app
#       #   run: |
#       #   npm run build --prod

#       # - name: Deploy to Ubuntu Server via SSH
#       #   script: |
#       #     sudo systemctl stop nginx
#       #     sudo cp -r ./client/dist/client/* /var/www/html/inventario
#       #     sudo systemctl start nginx
#       #     sudo systemctl restart nginx



#       # - name: Get last commit timestamp
#       #   run: |
#       #     LAST_COMMIT_TIMESTAMP=$(git log -1 --format=%ct)
#       #     echo "LAST_COMMIT_TIMESTAMP=$LAST_COMMIT_TIMESTAMP" >> $GITHUB_ENV

#       # - name: Get deployment timestamp
#       #   run: echo "DEPLOYMENT_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

#       # - name: Calculate lead time
#       #   run: |
#       #     LEAD_TIME=$(($DEPLOYMENT_TIMESTAMP - $LAST_COMMIT_TIMESTAMP))
#       #     echo "Lead Time: $LEAD_TIME seconds"
#       #     echo "LEAD_TIME=$LEAD_TIME" >> $GITHUB_ENV

#       # - name: Send lead time to Prometheus (Pushgateway)
#       #   run: |
#       #     curl -X POST http://18.207.191.94:9091/metrics/ \
#       #     --data "lead_time_seconds $LEAD_TIME"

#   env:
#     name: SET ENV
#     needs: start
#     runs-on: self-hosted
#     steps:
#       - name: ENV BACK
#         working-directory: ./
#         run: |
#           touch .env
#           echo "${{secrets.PROD_ENV_API }}" > .env
#           #echo DB_USER=${{ secrets.DB_USER }} >> .env
#           #echo DB_SERVER=${{ secrets.DB_SERVER }} >> .env
#           #echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
#           #echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> .env
#           #echo DB_PORT=${{ secrets.DB_PORT }} >> .env
#           #echo DB_NAME=${{ secrets.DB_NAME }} >> .env
#   build:
#     name: DEPLOY
#     needs: env
#     runs-on: self-hosted
#     steps:
#       - name: build
#         run: |
#           #sudo apt-get install -y docker-compose
#           #docker rm -f container-angular container-api-node container-nginx
#           #docker rmi -f angular node18 nginx
#           docker-compose up --build -d
#           #docker-compose -f ./docker/docker-compose.yml up --build -d