# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  start:
    name: PULL
    runs-on: self-hosted
   
    steps:
       - uses: actions/checkout@v4

  env:
    name: SET ENV
    needs: start
    runs-on: self-hosted
    steps:
      - name: ENV BACK
        working-directory: ./
        run: |
          touch .env
          echo "${{secrets.PROD_ENV_API }}" > .env

  build:
    name: DEPLOY
    needs: env
    runs-on: self-hosted
    steps:
      - name: build
        run: |
          #sudo apt-get install -y docker-compose
          #docker rm -f container-angular container-api-node container-nginx
          #docker rmi -f angular node18 nginx
          docker-compose up --build -d
          #docker-compose -f ./docker/docker-compose.yml up --build -d

  frontend:
    name: DEPLOY-FRONTEND
    runs-on: self-hosted
    steps:
      - name: build-angular
        run: |
          cd client
          npm run build --omit=dev
          sudo cp -r ./dist/client/* /var/www/

